In [2]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [8]:
mylist=[0,1,2,3,4,5]
arr=np.array(mylist)

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
print(type(mylist))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [17]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [20]:
np.arange(1,5)

array([1, 2, 3, 4])

In [21]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [23]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(5, dtype=int)


array([0, 0, 0, 0, 0])

In [29]:
np.zeros((2,2), dtype=int) #2 rows and 2 columns

array([[0, 0],
       [0, 0]])

In [30]:
np.zeros((2,10))  #2 rows and 10 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [32]:
np.zeros((10,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [34]:
np.ones(2)

array([1., 1.])

In [36]:
np.ones((2,2), dtype = int)

array([[1, 1],
       [1, 1]])

In [55]:
np.random.rand(3,5)

array([[0.81385497, 0.95638832, 0.44498542, 0.80891056, 0.09609242],
       [0.26401749, 0.44224119, 0.59809441, 0.58658452, 0.5165244 ],
       [0.33869744, 0.39930721, 0.16732863, 0.6276655 , 0.21144985]])

In [68]:
np.random.randint(4,19)

5

In [69]:
np.random.randint(2,20,4)

array([12, 18, 18, 17])

In [1]:
#create array using numy

import numpy as np

array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [7]:
import numpy as np
arr=np.array(42)
print(arr)

42


In [15]:
#2D array

import numpy as np
darray=np.array([[1,2,3],[4,5,6]])
print(darray)

[[1 2 3]
 [4 5 6]]


In [20]:
#3D array

import numpy as np
array=np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                   [[13, 14, 15, 16], [17, 18, 19, 20]]])

print (array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[13 14 15 16]
  [17 18 19 20]]]


In [21]:
import numpy

np.random.randint(1,12,10)   #create random 10 values between 1, 12 

array([8, 1, 5, 5, 5, 2, 1, 8, 8, 5])

In [22]:
import numpy

np.random.randint(10,40,(10,10))   # generate 10x10 matrix with elements between 10 to 40

array([[36, 32, 10, 15, 24, 31, 22, 12, 37, 34],
       [34, 23, 35, 29, 33, 11, 12, 16, 15, 29],
       [33, 31, 23, 22, 19, 24, 36, 36, 20, 35],
       [20, 10, 17, 31, 13, 18, 21, 20, 25, 14],
       [15, 11, 14, 21, 16, 20, 17, 12, 10, 16],
       [11, 32, 34, 20, 31, 31, 30, 30, 21, 33],
       [22, 15, 21, 28, 19, 31, 39, 14, 36, 37],
       [13, 25, 12, 27, 22, 15, 35, 19, 18, 18],
       [39, 25, 35, 24, 21, 33, 24, 16, 29, 16],
       [17, 18, 34, 31, 25, 14, 33, 38, 38, 24]])

In [23]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [25]:
np.arange(1,13).reshape(3,4)   # arrange elements beween 1 to 13 in 3x4 rows and colums

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
np.arange(1,13).reshape(4,3)  # 4X3 matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
b=np.random.randint(10, 40, (5,4))
b

array([[30, 11, 14, 35],
       [11, 36, 26, 21],
       [30, 28, 39, 24],
       [30, 18, 37, 37],
       [22, 28, 39, 34]])

In [31]:
b[:]

array([[30, 11, 14, 35],
       [11, 36, 26, 21],
       [30, 28, 39, 24],
       [30, 18, 37, 37],
       [22, 28, 39, 34]])

In [32]:
b[1:3]  # displays rows 1 and 2 

array([[11, 36, 26, 21],
       [30, 28, 39, 24]])

In [34]:
b[1,3]  # row 1, col 3rd 

21

In [35]:
b[1,-1]

21

In [37]:
b[2:3]

array([[30, 28, 39, 24]])

In [38]:
b[-5,3]

35

In [3]:
import numpy as np
arr2 = np.random.randint(0,100,(10,10))
print(arr2)

[[ 9 47 40 17 15 76 96 68  4 32]
 [17 18 46 93 25 65 42 54 34  1]
 [67 62 44 42 43 48 27 52 66 35]
 [54 23 11 61 49 86 30 87 53 60]
 [18 36 75 64 23 71 28 80 13  0]
 [ 0 46 96 22 17 87 65 81 46 28]
 [ 1  9 66 38 79 19 32 11 25 81]
 [30 35 79 66 17 38 35 88 91 85]
 [73 94 94 47 80 57 26 84 86 66]
 [76 31 76 73 70  3 45  5 45 62]]


In [4]:
arr2[0:10:3]

array([[ 9, 47, 40, 17, 15, 76, 96, 68,  4, 32],
       [54, 23, 11, 61, 49, 86, 30, 87, 53, 60],
       [ 1,  9, 66, 38, 79, 19, 32, 11, 25, 81],
       [76, 31, 76, 73, 70,  3, 45,  5, 45, 62]])

In [6]:
arr2.max()

96

In [10]:
import numpy as np
arr = np.arange(0,100,(10,10))
arr

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'