Multiple ways of creating arrays

In [15]:
import numpy as np

In [4]:
#create array with 0's and ones methods

arr_ones=np.ones(5)   #float by default
print(arr_ones)



[1. 1. 1. 1. 1.]


In [16]:
#create a 2D array

twod_array=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(twod_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [17]:
#check array dimenions
twod_array.ndim

3

SyntaxError: invalid syntax. Perhaps you forgot a comma? (658235685.py, line 1)

In [3]:
#create 1D array using array method

arr=np.array({1,2,3,4})
print(arr)
arr


{1, 2, 3, 4}


array({1, 2, 3, 4}, dtype=object)

In [5]:
#create array with 0's and ones methods

arr_ones=np.ones(5,dtype=int)   #use dtype for int
print(arr_ones)

[1 1 1 1 1]


In [9]:
arr=np.ones_like(arr_ones)  # creates arrays similar to existing array
print(arr)

[1 1 1 1 1]


In [10]:
rand_arr=np.random.rand(3,3)  # creates a 3x3 array with random float values
print(rand_arr)

[[0.32627394 0.82209763 0.95748365]
 [0.28303126 0.80125288 0.69189789]
 [0.443299   0.6865318  0.66619204]]


In [11]:
rand_arr_int=np.random.randint(1,10,5)  #randint(low, high=None, size=None, dtype=int)
print(rand_arr_int)

[3 3 8 5 3]


In [23]:
arr=np.array ( [[2,3,33,4,45],[23,45,56,66,2],[357,523,32,24,2],[32,32,44,33,234]])
print(arr)
arr.ndim

[[  2   3  33   4  45]
 [ 23  45  56  66   2]
 [357 523  32  24   2]
 [ 32  32  44  33 234]]


2

In [27]:
#array with different data types [float, complex, bool

float_arr=np.array([1,2,3],dtype=float)
print(float_arr)

bool_arr=np.array([1,0,1,0],dtype=bool)
print(bool_arr)

bool_arr=np.array([1,0,1,4],dtype=complex)
print(bool_arr)

[1. 2. 3.]
[ True False  True False]
[1.+0.j 0.+0.j 1.+0.j 4.+0.j]


In [28]:
np.identity(3)  #created array with 1's in the diagnol part of the matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
##arange and reshapw


twoD=np.arange(1,21).reshape(4,5)
print(twoD)

threeD=np.arange(8).reshape(2,2,2)
print(threeD)
threeD.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


3

In [45]:
arr=np.array([1,2,3])
print(arr)

#adding array elements with 2
arr +2

[1 2 3]


array([3, 4, 5])

In [46]:
arr=np.arange(1,29).reshape(4,7)
print(arr)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]]


In [47]:
arr=np.random.randint(1,29).reshape(4,7)
print(arr)

AttributeError: 'int' object has no attribute 'reshape'

In [52]:
np.random.random((2,4))

array([[0.81694649, 0.820451  , 0.97834406, 0.76993151],
       [0.27839489, 0.73764957, 0.91560377, 0.49693168]])

In [54]:
np.random.rand(2,4)

array([[0.64944814, 0.25548202, 0.02696073, 0.35257975],
       [0.64758061, 0.33736808, 0.28877635, 0.31193412]])

In [56]:
np.random.randint(2,4,10)

array([2, 2, 3, 3, 3, 3, 3, 3, 2, 3])

In [78]:
arr=np.random.randint(2,21,(2,10))
print(arr)

[[ 2 17 16 10 15  6 16 13  2  4]
 [13 17  8 11  5  6  4 20  6 20]]


In [80]:
arr.reshape(4,5)

array([[ 2, 17, 16, 10, 15],
       [ 6, 16, 13,  2,  4],
       [13, 17,  8, 11,  5],
       [ 6,  4, 20,  6, 20]])

In [81]:
arr.reshape(5,2,2)

array([[[ 2, 17],
        [16, 10]],

       [[15,  6],
        [16, 13]],

       [[ 2,  4],
        [13, 17]],

       [[ 8, 11],
        [ 5,  6]],

       [[ 4, 20],
        [ 6, 20]]])

In [82]:
p2 = np.arange(12).reshape(3,4)
p3 = np.arange(8).reshape(2,2,2)

In [83]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
print(p2)
print(p3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [93]:
p1 = np.random.random((2,2))
p1=np.round(p1)
p1

array([[0., 1.],
       [1., 1.]])

In [94]:
p2 = np.random.randint(1,10,(2,4))
p2

array([[8, 4, 3, 9],
       [6, 9, 8, 5]])

In [99]:
p3=np.random.randint(9,20,(4,2))
p3

array([[15,  9],
       [11, 15],
       [13, 12],
       [17, 13]])

In [102]:
np.dot(p2,p3)

array([[356, 285],
       [378, 350]])

In [101]:
print(p2)
print(p3)

[[8 4 3 9]
 [6 9 8 5]]
[[15  9]
 [11 15]
 [13 12]
 [17 13]]


In [103]:
p4 = np.arange(8).reshape(2,2,2)

In [104]:
p4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [105]:
p4.ndim

3

In [109]:
p5=np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[1,2,3],[4,5,6],[7,8,9]]])
print(p5)
p5.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

In [110]:
print(p2)
print(p3)

[[8 4 3 9]
 [6 9 8 5]]
[[15  9]
 [11 15]
 [13 12]
 [17 13]]


In [114]:
#fetching from arrays
p2[0,:]  #rows from r0 till all columns


array([8, 4, 3, 9])

In [113]:
p2[:,2]  #From Column2

array([3, 8])

In [115]:
p2[0, :3]

array([8, 4, 3])

In [118]:
p2[0:,1:3]

array([[4, 3],
       [9, 8]])

In [123]:
p5=np.arange(0,12).reshape(3,4)
print(p5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [125]:
#fetch 0,3 and 8,11 elements from p5 matrix

p5[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [132]:
p5[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [135]:
p5[1::1,]

3